debug: false
certManager:
  enabled: true
  spec:
    project: default
    source:
      path: common/cert-manager/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
certManagerKubeflowIssuer:
  enabled: true
  spec:
    selfSigned: {}
istioBase:
  enabled: true
  spec:
    project: default
    source:
      path: common/istio-1-23/istio-crds/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: istio-system
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true
#istioNamespace:
#  enabled: true
#  spec:
#    project: default
#    source:
#      path: common/istio-1-23/istio-namespace/base
#      repoURL: https://github.com/kubeflow/manifests
#      targetRevision: master
#    destination:
#      namespace: argocd
#      name: in-cluster
#    syncPolicy:
#      automated:
#        prune: true
#        selfHeal: true
#      syncOptions:
#        - CreateNamespace=true
#        - ServerSideApply=true
istioInstall:
  enabled: true
  spec:
    project: default
    source:
      path: common/istio-1-23/istio-install/overlays/oauth2-proxy
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: istio-system
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true
oauth2Proxy:
  enabled: true
  spec:
    project: default
    source:
      path: common/oauth2-proxy/overlays/m2m-dex-only/
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
dex:
  enabled: true
  spec:
    project: default
    source:
      path: common/dex/overlays/oauth2-proxy
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
centralDashboard:
  enabled: true
  spec:
    project: default
    source:
      path: apps/centraldashboard/overlays/oauth2-proxy
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
admissionWebhook:
  enabled: true
  spec:
    project: default
    source:
      path: apps/admission-webhook/upstream/overlays/cert-manager
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
istioResources:
  enabled: true
  spec:
    project: default
    source:
      path: common/istio-1-23/kubeflow-istio-resources/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
kubeflowRoles:
  enabled: true
  spec:
    project: default
    source:
      path: common/kubeflow-roles/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
exampleProfile:
  enabled: true
  spec:
    project: default
    source:
      path: common/user-namespace/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
notebookController:
  enabled: true
  spec:
    project: default
    source:
      path: apps/jupyter/notebook-controller/upstream/overlays/kubeflow
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        selfHeal: true
        prune: false
      syncOptions:
        - ServerSideApply=true
jupyterWebApp:
  enabled: true
  spec:
    project: default
    source:
      path: apps/jupyter/jupyter-web-app/upstream/overlays/istio
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        selfHeal: true
        prune: false
      syncOptions:
        - ServerSideApply=true
pvcViewerController:
  enabled: true
  spec:
    project: default
    source:
      path: apps/pvcviewer-controller/upstream/default
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        selfHeal: true
        prune: false
      syncOptions:
        - ServerSideApply=true
volumesWebApp:
  enabled: true
  spec:
    project: default
    source:
      path: apps/volumes-web-app/upstream/overlays/istio
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        selfHeal: true
        prune: false
      syncOptions:
        - ServerSideApply=true
profiles:
  enabled: true
  spec:
    project: default
    source:
      path: apps/profiles/upstream/overlays/kubeflow
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        selfHeal: true
        prune: false
      syncOptions:
        - ServerSideApply=true
networkPolicies:
  enabled: true
  spec:
    project: default
    source:
      path: common/networkpolicies/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        selfHeal: true
        prune: false
      syncOptions:
        - ServerSideApply=true
kubeflowPipelines:
  enabled: true
  spec:
    project: default
    source:
      path: apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
      kustomize:
        patches:
          - target:
              kind: Deployment
              name: ml-pipeline
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
          - target:
              kind: Deployment
              name: ml-pipeline-persistenceagent
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
          - target:
              kind: Deployment
              name: workflow-controller
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
          - target:
              kind: Deployment
              name: mysql
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
          - target:
              kind: StatefulSet
              name: metacontroller
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        selfHeal: true
        prune: false
      syncOptions:
        - ServerSideApply=true
